activity: /help
owners:
  - "311929179186790400"
  - "422418878459674624"
systemServer:
  - "1313550337474429001"
intents:
  - Guilds
  - GuildMembers
  - GuildModeration
  - GuildBans
  - GuildEmojisAndStickers
  - GuildIntegrations
  - GuildWebhooks
  - GuildInvites
  - GuildVoiceStates
  - GuildPresences
  - GuildMessages
  - GuildMessageReactions
  - GuildMessageTyping
  - DirectMessages
  - DirectMessageReactions
  - DirectMessageTyping
  - MessageContent
  - GuildScheduledEvents
  - AutoModerationConfiguration
  - AutoModerationExecution
  - GuildMessagePolls
  - DirectMessagePolls
partials:
  - Reaction
  - Message
