flags:
  list:
    title: "ğŸš© <user>'s flags:"
    flags:
      OWNER: "**Bot Owner**: This user is a developer of this bot"
      STAFF: "**Bot Staff**: This user has staff priviliges on this bot"
      PREMIUM: "**Premium**: This user supported the development of this bot"
      BLACKLISTED: "**Blacklisted**: This user is blacklisted from this bot"
    none: ğŸš© <user> has no flags
  add: âœ… Flag `<flag>` has been assigned to <user>
  remove: âœ… Flag `<flag>` has been removed to <user>
  errors:
    alreadyHasFlag: âš ï¸ Flag already assigned
    notHasFlag: âš ï¸ Nothing to remove
